name = "modpack_dos_guri"
author = "Flavio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "551df8150f6d531b879ca11033c55524556f0e10f6a9980505b17b159c474ef6"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
