name = "modpack_dos_guri"
author = "Flavio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "479e098156a5dc2b934eb67b238a986509c60d06ec83edaf77bbc49e84c89712"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
