name = "modpack_dos_guri"
author = "Flavio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17910e8397b739de9edc8eb1c79b813b8e5f14eaf1648c4e86d0a8df70ddaf09"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
